name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  # This workflow contains a single job called "build"
  build-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout 
        uses: actions/checkout@master

      - name: install racket
        uses: Bogdanp/setup-racket@v1.7 # see https://github.com/Bogdanp/setup-racket for more info
        with:
          architecture: 'x64'
          distribution: 'full'
          variant: 'CS'
          version: 'stable'
      - name: install base package
        run: |
          raco pkg install --batch --auto ./fsm-lib ./fsm-doc/ ./fsm
          raco setup --pkgs fsm fsm-lib
