name: Scribble-Deploy

on:
  push:
    branches: [ master ]
    paths:
    - 'fsm/fsm-doc/**'
    - '.github/workflows/scribble.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'fsm/fsm-doc/**'
      - '.github/workflows/scribble.yml'

jobs:
  publish:
    runs-on: 'ubuntu-latest'
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: install racket
      uses: Bogdanp/setup-racket@v1.7
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: 'stable'
    - name: install base package
      run: raco pkg install --batch --auto fsm-lib fsm-doc fsm
    - name: build docs
      run: scribble +m --redirect-main http://pkg-build.racket-lang.org/doc/ --htmls --dest ./docs ./fsm/fsm-doc/scribblings/fsm.scrbl
    - name: push to gh-pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        folder: docs/fsm-doc
        branch: master